/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidjni002_JniTest */

#ifndef _Included_com_example_androidjni002_JniTest
#define _Included_com_example_androidjni002_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidjni002_JniTest
 * Method:    getCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidjni002_JniTest_getCount
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
